apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-app
  namespace: cloud-app-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cloud-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: cloud-app
    spec:
      containers:
      - name: cloud-app
        image: $DOCKERHUB_USERNAME/cloud-app:latest  # Use env var for username, tag for latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: prod
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://postgres-service.cloud-app-ns.svc.cluster.local:5432/cloud_app_db
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        readinessProbe:
            httpGet:
              path: /  # Adjust if endpoint differs
              port: 8080
            initialDelaySeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-app-service
  namespace: cloud-app-ns
spec:
  selector:
    app: cloud-app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30000
  type: NodePort