name: CI/CD Docker Build & Push

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    # Use GitHub-hosted runner for building & pushing to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Generate version number
        id: version
        run: |
          # Create a unique version based on date, time and commit hash
          VERSION=$(date +'%Y%m%d%H%M')-${GITHUB_SHA::7}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew bootJar

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/cloud-app:${{ env.VERSION }} .
          # Also tag as latest for convenience
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/cloud-app:${{ env.VERSION }} ${{ secrets.DOCKERHUB_USERNAME }}/cloud-app:latest

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/cloud-app:${{ env.VERSION }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/cloud-app:latest
